
enum class QueryType : uint32_t {
	AUTHORIZATION,
	REGISTRATION,
	CREATE_CHAT,
	UPDATE_MY_NAME,
	UPDATE_MY_PASSWORD,
	UPDATE_MY_PHOTO,
	LOAD_FRIEND_INFO,
	LOAD_ALL_FRIENDS_STATUSES,
	MESSAGE,
	MESSAGES_READ_CONFIRMATION,
	STATUS,
	_,
	AUTHORIZATION_SUCCESS,
	AUTHORIZATION_FAIL,
	REGISTRATION_SUCCESS,
	REGISTRATION_FAIL,
	FRIENDS_STATUSES,
	CHAT_CREATE_SUCCESS,
	CHAT_CREATE_FAIL,
	USER_INFO
};